{{- if .Values.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app.configMapName" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{- if not (kindIs "map" $value) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.config.additionalVars }}
    {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
